### PR TITLE
CI: Upgrade clang-format 10 -> 11

### PR DESCRIPTION
**Pull request by Kissaki**

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
What's the reason for this switch? Presumably this collides with existing formatting in this repo, no? :thinking:

**Comment by Kissaki** [comment]
Isn't the formatting defined in [`.clang-format`](https://github.com/mumble-voip/mumble-json-bridge/blob/master/.clang-format)?

I would expect upgrading clang-format to not lead to changes?

I initially set this branch and PR up trying to fix the build/checks in master, but I was able to fix it with upgrading the used GitHub action, that was sufficient. I left this open planning to (maybe/probably) upgrade the clang-format version expecting no difference in the actual formatting verification, only an upgrade in tooling.

**Comment by davidebeatrici** [comment]
Unfortunately yes, different `clang-format` versions can lead to a different output due to bug fixes and overall changes.

**Comment by Krzmbrzl** [comment]
Yeah, clang-format only produces equal outputs for equal versions. That's a big shame, but that's how it is.

**Comment by Kissaki** [comment]
Shall I discard this then?

The [action has versions up to 18](https://github.com/marketplace/actions/clang-format-check), which I would have tried.

If the pr checks do not report any issue then the upgrade should be fine even without code changes!?

At least the current PR state upgrading from 10 to 11 doesn't report and changes!?

In the log I don't even see a success message. So I assume it only reports issues? https://github.com/mumble-voip/mumble-json-bridge/actions/runs/8253456912/job/22575337407?pr=10

**Comment by Kissaki** [comment]
ok, v 18 fails :D

I guess I'll close instead of finding max version, nobody's using this project anyway

**Comment by Kissaki** [comment]
> nobody's using this project anyway

I thought I was in mumblekit…

**Pull request closed without merging**
